export const allQuestions = {
  general: [
    { question: "¿Cuál es la capital de Francia?", options: ["París", "Londres", "Berlín", "Roma"], answer: "París" },
    { question: "¿Cuántos continentes hay?", options: ["5", "6", "7", "8"], answer: "7" },
    { question: "¿En qué año llegó el hombre a la Luna?", options: ["1965", "1969", "1972", "1980"], answer: "1969" },
    { question: "¿Cuál es el océano más grande?", options: ["Atlántico", "Índico", "Pacífico", "Ártico"], answer: "Pacífico" },
    { question: "¿Cuál es el metal más ligero?", options: ["Aluminio", "Titanio", "Litio", "Hierro"], answer: "Litio" },
    { question: "¿Qué gas respiramos para vivir?", options: ["Oxígeno", "Nitrógeno", "Dióxido de carbono", "Helio"], answer: "Oxígeno" },
    { question: "¿Qué instrumento mide la temperatura?", options: ["Barómetro", "Termómetro", "Anemómetro", "Higrómetro"], answer: "Termómetro" },
    { question: "¿Cuál es el planeta más grande del sistema solar?", options: ["Marte", "Júpiter", "Saturno", "Venus"], answer: "Júpiter" },
    { question: "¿Qué país tiene la mayor población?", options: ["India", "EEUU", "China", "Rusia"], answer: "China" },
    { question: "¿Quién escribió 'Don Quijote'?", options: ["Cervantes", "Shakespeare", "Tolstoi", "Poe"], answer: "Cervantes" },
    { question: "¿Cuál es el idioma más hablado en el mundo?", options: ["Inglés", "Chino mandarín", "Español", "Hindi"], answer: "Chino mandarín" },
    { question: "¿Cuál es la moneda oficial de Japón?", options: ["Yen", "Dólar", "Euro", "Peso"], answer: "Yen" },
      { question: "¿Cuál es el símbolo químico del oro?", options: ["Au", "Ag", "O", "Fe"], answer: "Au" },
  { question: "¿Qué país ganó el Mundial de Fútbol 2018?", options: ["Alemania", "Brasil", "Francia", "Croacia"], answer: "Francia" },
  { question: "¿En qué año comenzó la Segunda Guerra Mundial?", options: ["1939", "1945", "1914", "1929"], answer: "1939" },
  { question: "¿Cuál es el monte más alto del mundo?", options: ["Everest", "K2", "Kangchenjunga", "Makalu"], answer: "Everest" },
  { question: "¿Qué elemento químico tiene el número atómico 1?", options: ["Oxígeno", "Hidrógeno", "Carbono", "Nitrógeno"], answer: "Hidrógeno" },
  { question: "¿Quién fue el primer presidente de Estados Unidos?", options: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"], answer: "George Washington" },
  { question: "¿Qué país tiene forma de bota?", options: ["Italia", "Portugal", "Grecia", "Chile"], answer: "Italia" },
  { question: "¿Cuál es el animal más rápido del mundo?", options: ["Guepardo", "León", "Halcón peregrino", "Antílope"], answer: "Halcón peregrino" },
  { question: "¿Cuántos colores tiene el arcoíris?", options: ["5", "6", "7", "8"], answer: "7" },
  { question: "¿Cuál es el país más pequeño del mundo?", options: ["Mónaco", "San Marino", "Vaticano", "Liechtenstein"], answer: "Vaticano" },
  { question: "¿Qué filósofo escribió 'La República'?", options: ["Platón", "Aristóteles", "Sócrates", "Descartes"], answer: "Platón" },
  { question: "¿En qué continente se encuentra Egipto?", options: ["Asia", "Europa", "África", "Oceanía"], answer: "África" },
  { question: "¿Cuál es la capital de Canadá?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: "Ottawa" },
  { question: "¿Cuál es el idioma oficial de Brasil?", options: ["Español", "Portugués", "Francés", "Inglés"], answer: "Portugués" },
  { question: "¿Quién escribió 'Cien años de soledad'?", options: ["Gabriel García Márquez", "Pablo Neruda", "Mario Vargas Llosa", "Jorge Luis Borges"], answer: "Gabriel García Márquez" },
  { question: "¿Qué órgano del cuerpo produce la insulina?", options: ["Hígado", "Páncreas", "Riñón", "Estómago"], answer: "Páncreas" },
  { question: "¿Cuál es la fórmula química del agua?", options: ["H2O", "CO2", "O2", "NaCl"], answer: "H2O" },
  { question: "¿Cuál es la capital de Australia?", options: ["Sídney", "Melbourne", "Canberra", "Perth"], answer: "Canberra" },
  { question: "¿Quién descubrió América?", options: ["Cristóbal Colón", "Américo Vespucio", "Marco Polo", "Hernán Cortés"], answer: "Cristóbal Colón" },
  { question: "¿Cuál es el país más grande del mundo en superficie?", options: ["China", "Canadá", "Rusia", "EE.UU."], answer: "Rusia" },
  { question: "¿Qué animal es conocido por su memoria?", options: ["Elefante", "Perro", "Delfín", "Gato"], answer: "Elefante" },
  { question: "¿Qué tipo de animal es la ballena?", options: ["Pez", "Mamífero", "Reptil", "Anfibio"], answer: "Mamífero" },
  { question: "¿Cuántos dientes tiene un adulto normalmente?", options: ["28", "30", "32", "34"], answer: "32" },
  { question: "¿Cuál es el país de origen del sushi?", options: ["Corea", "China", "Japón", "Tailandia"], answer: "Japón" },
  { question: "¿Quién pintó 'La noche estrellada'?", options: ["Van Gogh", "Monet", "Dalí", "Matisse"], answer: "Van Gogh" },
  { question: "¿Cuál es el hueso más largo del cuerpo humano?", options: ["Fémur", "Húmero", "Tibia", "Columna"], answer: "Fémur" },
  { question: "¿Cuántos lados tiene un hexágono?", options: ["5", "6", "7", "8"], answer: "6" },
  { question: "¿Cuál es el continente con más países?", options: ["Asia", "África", "Europa", "América"], answer: "África" },
  { question: "¿Qué científico formuló la teoría de la relatividad?", options: ["Einstein", "Newton", "Tesla", "Hawking"], answer: "Einstein" },
  { question: "¿Qué gas es más abundante en la atmósfera?", options: ["Oxígeno", "Nitrógeno", "CO2", "Argón"], answer: "Nitrógeno" },
  { question: "¿Qué día se celebra el Día de la Tierra?", options: ["22 de abril", "5 de junio", "1 de mayo", "25 de diciembre"], answer: "22 de abril" },
  { question: "¿Qué escritor creó a Sherlock Holmes?", options: ["Arthur Conan Doyle", "Agatha Christie", "Poe", "H.G. Wells"], answer: "Arthur Conan Doyle" },
  { question: "¿En qué país se encuentra Machu Picchu?", options: ["México", "Chile", "Perú", "Ecuador"], answer: "Perú" },
  { question: "¿Qué instrumento tiene teclas, cuerdas y martillos?", options: ["Piano", "Guitarra", "Violín", "Arpa"], answer: "Piano" },
  { question: "¿Qué planeta es conocido como el planeta rojo?", options: ["Marte", "Venus", "Júpiter", "Saturno"], answer: "Marte" },
  { question: "¿Cuál es el mamífero más grande del mundo?", options: ["Elefante", "Ballena azul", "Jirafa", "Hipopótamo"], answer: "Ballena azul" },
  { question: "¿Quién escribió 'Hamlet'?", options: ["Shakespeare", "Cervantes", "Goethe", "Homero"], answer: "Shakespeare" },
  { question: "¿Cuál es el órgano más grande del cuerpo humano?", options: ["Hígado", "Piel", "Pulmón", "Cerebro"], answer: "Piel" },
  { question: "¿Cuál es el planeta más cercano al sol?", options: ["Mercurio", "Venus", "Marte", "Tierra"], answer: "Mercurio" },
  { question: "¿Cuál es la capital de Argentina?", options: ["Buenos Aires", "Lima", "Montevideo", "Santiago"], answer: "Buenos Aires" },
  { question: "¿Qué parte del cuerpo humano produce glóbulos rojos?", options: ["Médula ósea", "Corazón", "Hígado", "Riñón"], answer: "Médula ósea" },
  { question: "¿Qué civilización construyó las pirámides?", options: ["Egipcia", "Azteca", "Inca", "Griega"], answer: "Egipcia" },
  { question: "¿En qué país se encuentra la Gran Muralla?", options: ["China", "India", "Japón", "Corea"], answer: "China" },
  { question: "¿Qué instrumento se asocia con Antonio Vivaldi?", options: ["Violín", "Piano", "Flauta", "Órgano"], answer: "Violín" },
  { question: "¿Cuál es el océano más pequeño del mundo?", options: ["Ártico", "Índico", "Atlántico", "Pacífico"], answer: "Ártico" },
  { question: "¿Qué país tiene más islas?", options: ["Indonesia", "Suecia", "Filipinas", "Canadá"], answer: "Suecia" },
  { question: "¿Cuál es el primer elemento de la tabla periódica?", options: ["Hidrógeno", "Helio", "Litio", "Oxígeno"], answer: "Hidrógeno" },
    { question: "¿Cuál es el nombre del satélite natural de Marte?", options: ["Fobos", "Deimos", "Europa", "Titan"], answer: "Fobos" },
  { question: "¿Quién formuló la ley de la gravedad?", options: ["Galileo Galilei", "Isaac Newton", "Albert Einstein", "Nikola Tesla"], answer: "Isaac Newton" },
  { question: "¿Cuál es la capital de Mongolia?", options: ["Ulan Bator", "Astana", "Tiflis", "Bishkek"], answer: "Ulan Bator" },
  { question: "¿En qué año se firmó la paz de Westfalia que terminó la Guerra de los Treinta Años?", options: ["1618", "1648", "1701", "1713"], answer: "1648" },
  { question: "¿Qué país tiene la mayor cantidad de Patrimonios de la Humanidad UNESCO?", options: ["Italia", "China", "España", "Francia"], answer: "Italia" },
  { question: "¿Qué partícula subatómica tiene carga positiva?", options: ["Electrón", "Protón", "Neutrón", "Positrón"], answer: "Protón" },
  { question: "¿Cuál es el libro más traducido después de la Biblia?", options: ["El Quijote", "El Principito", "La Odisea", "El Corán"], answer: "El Principito" },
  { question: "¿Qué civilización antigua creó el sistema de escritura cuneiforme?", options: ["Egipcia", "Mesopotámica", "Inca", "Azteca"], answer: "Mesopotámica" },
  { question: "¿Qué artista es famoso por pintar el techo de la Capilla Sixtina?", options: ["Miguel Ángel", "Leonardo da Vinci", "Raphael", "Caravaggio"], answer: "Miguel Ángel" },
  { question: "¿Cuál es el gas noble más abundante en la atmósfera terrestre?", options: ["Argón", "Neón", "Helio", "Kriptón"], answer: "Argón" },
  { question: "¿Qué país es el mayor productor mundial de café?", options: ["Colombia", "Brasil", "Vietnam", "Etiopía"], answer: "Brasil" },
  { question: "¿Qué instrumento mide la presión atmosférica?", options: ["Barómetro", "Higrómetro", "Termómetro", "Anemómetro"], answer: "Barómetro" },
  { question: "¿Cuál es la moneda oficial de Suiza?", options: ["Euro", "Franco suizo", "Dólar", "Corona"], answer: "Franco suizo" },
  { question: "¿Quién es el autor de la teoría del psicoanálisis?", options: ["Carl Jung", "Sigmund Freud", "Alfred Adler", "Ivan Pavlov"], answer: "Sigmund Freud" },
  { question: "¿En qué año se inauguró la Torre Eiffel?", options: ["1887", "1889", "1892", "1900"], answer: "1889" },
  { question: "¿Qué país tiene la mayor cantidad de volcanes activos?", options: ["Indonesia", "Japón", "Italia", "Estados Unidos"], answer: "Indonesia" },
  { question: "¿Cuál es la capital de Kazajistán?", options: ["Astana", "Tashkent", "Bishkek", "Ulan Bator"], answer: "Astana" },
  { question: "¿Qué metal es líquido a temperatura ambiente?", options: ["Mercurio", "Plomo", "Oro", "Cobre"], answer: "Mercurio" },
  { question: "¿Quién fue el primer hombre en orbitar la Tierra?", options: ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "Alan Shepard"], answer: "Yuri Gagarin" },
  { question: "¿Qué es la Ley de Ohm?", options: ["Relación entre voltaje, corriente y resistencia", "Ley del movimiento", "Principio de la relatividad", "Ley de conservación de la energía"], answer: "Relación entre voltaje, corriente y resistencia" },
  { question: "¿Cuál es el nombre del pintor impresionista que creó 'Impresión, sol naciente'?", options: ["Claude Monet", "Edgar Degas", "Vincent van Gogh", "Paul Cézanne"], answer: "Claude Monet" },
  { question: "¿Qué es un haiku?", options: ["Poema japonés de tres versos y 17 sílabas", "Canción tradicional china", "Baile folclórico", "Instrumento musical"], answer: "Poema japonés de tres versos y 17 sílabas" },
  { question: "¿Cuál es el principal idioma oficial de Suiza?", options: ["Francés", "Alemán", "Italiano", "Los cuatro son oficiales"], answer: "Los cuatro son oficiales" },
  { question: "¿En qué país se encuentra el desierto del Sahara?", options: ["Argelia", "Egipto", "Niger", "Todos los anteriores"], answer: "Todos los anteriores" },
  { question: "¿Qué ciudad es conocida como la 'Ciudad Eterna'?", options: ["Roma", "Atenas", "Jerusalén", "Estambul"], answer: "Roma" },
  { question: "¿Cuál es el nombre del símbolo químico del plomo?", options: ["Pb", "Pl", "Po", "Pd"], answer: "Pb" },
  { question: "¿Quién fue la primera mujer en ganar un Premio Nobel?", options: ["Marie Curie", "Rosalind Franklin", "Dorothy Hodgkin", "Ada Lovelace"], answer: "Marie Curie" },
  { question: "¿Cuál es la distancia aproximada entre la Tierra y el Sol?", options: ["150 millones de km", "100 millones de km", "250 millones de km", "500 millones de km"], answer: "150 millones de km" },
  { question: "¿Qué enfermedad fue erradicada gracias a la vacunación?", options: ["Viruela", "Polio", "Sarampión", "Tuberculosis"], answer: "Viruela" },
  { question: "¿Qué país tiene la mayor red de metro del mundo?", options: ["Estados Unidos", "China", "Rusia", "Japón"], answer: "China" },
  { question: "¿Quién fue el líder de la Revolución Rusa de 1917?", options: ["Lenin", "Stalin", "Trotsky", "Kerenski"], answer: "Lenin" },
  { question: "¿Cuál es la capital de Nueva Zelanda?", options: ["Auckland", "Christchurch", "Wellington", "Hamilton"], answer: "Wellington" },
  { question: "¿Qué científico es conocido por sus leyes del movimiento?", options: ["Galileo Galilei", "Isaac Newton", "Albert Einstein", "Johannes Kepler"], answer: "Isaac Newton" },
  { question: "¿Cuál es el nombre de la capa más externa de la Tierra?", options: ["Manto", "Núcleo", "Corteza", "Litosfera"], answer: "Corteza" },
  { question: "¿Qué es la fotosíntesis?", options: ["Proceso por el cual las plantas producen energía usando luz solar", "Método para purificar agua", "Tipo de respiración", "Proceso de descomposición"], answer: "Proceso por el cual las plantas producen energía usando luz solar" },
  { question: "¿Cuál es el nombre del río más largo del mundo?", options: ["Amazonas", "Nilo", "Yangtsé", "Misisipi"], answer: "Amazonas" },
  { question: "¿Cuál es el continente con mayor diversidad lingüística?", options: ["Asia", "África", "Europa", "América"], answer: "África" },
  { question: "¿Qué teoría propuso Charles Darwin?", options: ["Evolución por selección natural", "Teoría de la relatividad", "Genética mendeliana", "Teoría celular"], answer: "Evolución por selección natural" },
  { question: "¿Quién fue el arquitecto del Taj Mahal?", options: ["Ustad Ahmad Lahori", "Babur", "Shah Jahan", "Akbar"], answer: "Ustad Ahmad Lahori" },
  { question: "¿Qué país fue gobernado por Augusto Pinochet?", options: ["Argentina", "Chile", "Perú", "Bolivia"], answer: "Chile" },
  { question: "¿Cuál es la unidad básica de la vida?", options: ["Célula", "Molécula", "Átomo", "Órgano"], answer: "Célula" },
  { question: "¿Cuál es el nombre del volcán activo más alto del mundo?", options: ["Cotopaxi", "Ojos del Salado", "Mauna Loa", "Etna"], answer: "Ojos del Salado" },
  { question: "¿Quién fue el primer hombre en cruzar el Canal de la Mancha nadando?", options: ["Matthew Webb", "Michael Phelps", "Mark Spitz", "Johnny Weissmuller"], answer: "Matthew Webb" },
  { question: "¿Qué filósofo griego fue maestro de Alejandro Magno?", options: ["Sócrates", "Platón", "Aristóteles", "Epicuro"], answer: "Aristóteles" },
  { question: "¿Cuál es el nombre del satélite natural de Júpiter más grande?", options: ["Io", "Europa", "Ganimedes", "Calisto"], answer: "Ganimedes" },
  { question: "¿Qué país ganó la Guerra de los Cien Años?", options: ["Inglaterra", "Francia", "España", "Portugal"], answer: "Francia" },
  { question: "¿Qué inventor es conocido por la bombilla eléctrica?", options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "Michael Faraday"], answer: "Thomas Edison" },
  { question: "¿Cuál es el nombre del sistema de escritura usado por los antiguos egipcios?", options: ["Cuneiforme", "Jeroglíficos", "Sánscrito", "Alfabeto fenicio"], answer: "Jeroglíficos" },
  { question: "¿Qué elemento es esencial para la respiración celular?", options: ["Oxígeno", "Carbono", "Nitrógeno", "Hidrógeno"], answer: "Oxígeno" },
    { question: "¿Cuál es el nombre del arquitecto que diseñó la Sagrada Familia?", options: ["Antoni Gaudí", "Le Corbusier", "Frank Lloyd Wright", "Zaha Hadid"], answer: "Antoni Gaudí" },
  { question: "¿Qué civilización construyó la ciudad de Petra?", options: ["Nabateos", "Romanos", "Egipcios", "Griegos"], answer: "Nabateos" },
  { question: "¿Cuál es el mineral más duro conocido?", options: ["Diamante", "Corindón", "Topacio", "Granate"], answer: "Diamante" },
  { question: "¿Quién escribió 'La Divina Comedia'?", options: ["Dante Alighieri", "Boccaccio", "Petrarca", "Goethe"], answer: "Dante Alighieri" },
  { question: "¿En qué año se creó la Organización de las Naciones Unidas (ONU)?", options: ["1945", "1919", "1950", "1939"], answer: "1945" },
  { question: "¿Cuál es la capital de Mongolia?", options: ["Ulan Bator", "Almaty", "Astana", "Tashkent"], answer: "Ulan Bator" },
  { question: "¿Qué científico descubrió la penicilina?", options: ["Alexander Fleming", "Louis Pasteur", "Marie Curie", "Gregor Mendel"], answer: "Alexander Fleming" },
  { question: "¿Cuál es el país con más lenguas oficiales?", options: ["Sudáfrica", "India", "Suiza", "Canadá"], answer: "Sudáfrica" },
  { question: "¿Qué autor es conocido por la obra 'Crimen y Castigo'?", options: ["Fiódor Dostoievski", "León Tolstói", "Antón Chéjov", "Nikolái Gógol"], answer: "Fiódor Dostoievski" },
  { question: "¿Cuál es la mayor luna de Saturno?", options: ["Titán", "Rea", "Encélado", "Dione"], answer: "Titán" },
  { question: "¿En qué país se originó la filosofía estoica?", options: ["Grecia", "Roma", "Egipto", "Persia"], answer: "Grecia" },
  { question: "¿Qué es la leyenda del Rey Arturo asociada principalmente?", options: ["Excalibur", "La Mesa Redonda", "Camelot", "Todos los anteriores"], answer: "Todos los anteriores" },
  { question: "¿Cuál es el nombre del proceso de división celular en organismos eucariotas?", options: ["Mitosis", "Meiosis", "Fagocitosis", "Endocitosis"], answer: "Mitosis" },
  { question: "¿Quién compuso la Novena Sinfonía?", options: ["Beethoven", "Mozart", "Bach", "Chopin"], answer: "Beethoven" },
  { question: "¿Qué país tiene la mayor extensión de selva tropical?", options: ["Brasil", "República Democrática del Congo", "Indonesia", "Perú"], answer: "Brasil" },
  { question: "¿Qué acontecimiento marcó el inicio de la Edad Moderna?", options: ["Caída del Imperio Romano", "Descubrimiento de América", "Revolución Francesa", "Reforma Protestante"], answer: "Descubrimiento de América" },
  { question: "¿Cuál es la capital de Burkina Faso?", options: ["Uagadugú", "Ouagadougou", "Bamako", "Niamey"], answer: "Ouagadougou" },
  { question: "¿Qué invento es atribuido a Johannes Gutenberg?", options: ["Imprenta", "Telescopio", "Reloj mecánico", "Microscopio"], answer: "Imprenta" },
  { question: "¿Cuál es el nombre del primer satélite artificial lanzado al espacio?", options: ["Sputnik 1", "Explorer 1", "Apollo 11", "Vostok 1"], answer: "Sputnik 1" },
  { question: "¿Cuál es el nombre de la moneda de Turquía?", options: ["Lira turca", "Dólar", "Euro", "Rublo"], answer: "Lira turca" },
  { question: "¿Qué órgano humano produce bilis?", options: ["Hígado", "Páncreas", "Riñón", "Vesícula biliar"], answer: "Hígado" },
  { question: "¿Cuál es la capital de Tayikistán?", options: ["Dusambé", "Biskek", "Ashgabat", "Tashkent"], answer: "Dusambé" },
  { question: "¿Quién fue el autor del manifiesto comunista?", options: ["Karl Marx", "Vladimir Lenin", "Friedrich Engels", "Lenin y Marx"], answer: "Karl Marx y Friedrich Engels" },
  { question: "¿Qué país tiene el mayor número de desiertos?", options: ["Australia", "China", "Estados Unidos", "Arabia Saudita"], answer: "Australia" },
  { question: "¿Qué ciudad fue la capital del Imperio Azteca?", options: ["Tenochtitlán", "Teotihuacán", "Chichén Itzá", "Palenque"], answer: "Tenochtitlán" },
  { question: "¿Qué océano está entre África y Australia?", options: ["Atlántico", "Pacífico", "Índico", "Ártico"], answer: "Índico" },
  { question: "¿Cuál es la lengua con más hablantes nativos en Europa?", options: ["Inglés", "Alemán", "Francés", "Ruso"], answer: "Ruso" },
  { question: "¿Qué animal es conocido por construir presas?", options: ["Castor", "Nutria", "Cangrejo", "Rana"], answer: "Castor" },
  { question: "¿Qué país tiene la mayor producción de petróleo?", options: ["Estados Unidos", "Arabia Saudita", "Rusia", "Irak"], answer: "Estados Unidos" },
  { question: "¿Qué escritor es conocido por '1984' y 'Rebelión en la granja'?", options: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Philip K. Dick"], answer: "George Orwell" },
  { question: "¿Cuál es el nombre de la capa de gases que protege la Tierra de los rayos UV?", options: ["Ozono", "Dióxido de carbono", "Nitrógeno", "Argón"], answer: "Ozono" },
  { question: "¿Cuál es la capital de Eslovenia?", options: ["Ljubljana", "Zagreb", "Bratislava", "Sarajevo"], answer: "Ljubljana" },
  { question: "¿Qué descubrimiento hizo Marie Curie?", options: ["Radioactividad", "Penicilina", "Vacuna contra la polio", "Teoría del átomo"], answer: "Radioactividad" },
  { question: "¿Cuál es el río más largo de Europa?", options: ["Danubio", "Volga", "Rin", "Loira"], answer: "Volga" },
  { question: "¿Cuál es el nombre del monoteísmo más antiguo?", options: ["Zoroastrismo", "Cristianismo", "Judaísmo", "Islam"], answer: "Zoroastrismo" },
  { question: "¿Cuál es el nombre del pintor de 'Las meninas'?", options: ["Diego Velázquez", "El Greco", "Goya", "Picasso"], answer: "Diego Velázquez" },
  { question: "¿En qué año cayó el Muro de Berlín?", options: ["1989", "1991", "1987", "1990"], answer: "1989" },
  { question: "¿Qué imperio construyó la ciudad de Machu Picchu?", options: ["Inca", "Azteca", "Maya", "Olmeca"], answer: "Inca" },
  { question: "¿Cuál es el órgano que regula el equilibrio y la coordinación?", options: ["Cerebelo", "Cerebro", "Hipotálamo", "Tálamo"], answer: "Cerebelo" },
  { question: "¿Quién fue la primera persona en ganar dos premios Nobel en distintas ciencias?", options: ["Marie Curie", "Linus Pauling", "Albert Einstein", "Isaac Newton"], answer: "Marie Curie" },
  { question: "¿Cuál es la lengua oficial de Etiopía?", options: ["Amárico", "Swahili", "Árabe", "Somalí"], answer: "Amárico" },
  { question: "¿Qué estructura anatómica conecta los músculos a los huesos?", options: ["Tendones", "Ligamentos", "Cartílagos", "Fascias"], answer: "Tendones" },
  ],
  science: [
    { question: "¿Qué partícula tiene carga positiva?", options: ["Neutrón", "Protón", "Electrón", "Quark"], answer: "Protón" },
    { question: "¿Qué es H2O?", options: ["Oxígeno", "Agua", "Dióxido de carbono", "Hidrógeno"], answer: "Agua" },
    { question: "¿Cuál es la fórmula de la velocidad?", options: ["d/t", "m/v", "f/a", "p=v/t"], answer: "d/t" },
    { question: "¿Qué organelo produce energía en la célula?", options: ["Núcleo", "Mitocondria", "Ribosoma", "Cloroplasto"], answer: "Mitocondria" },
    { question: "¿Qué fuerza mantiene los planetas en órbita?", options: ["Magnetismo", "Gravedad", "Electricidad", "Fricción"], answer: "Gravedad" },
    { question: "¿Qué gas exhalamos al respirar?", options: ["Oxígeno", "Nitrógeno", "Dióxido de carbono", "Argón"], answer: "Dióxido de carbono" },
    { question: "¿Cuál es el estado sólido del agua?", options: ["Hielo", "Vapor", "Líquido", "Gas"], answer: "Hielo" },
    { question: "¿Qué tipo de energía produce la luz solar?", options: ["Térmica", "Química", "Electromagnética", "Nuclear"], answer: "Electromagnética" },
    { question: "¿Cuál es el elemento químico con símbolo 'O'?", options: ["Oro", "Oxígeno", "Osmio", "Plomo"], answer: "Oxígeno" },
    { question: "¿Qué planeta es conocido como el planeta rojo?", options: ["Venus", "Marte", "Saturno", "Mercurio"], answer: "Marte" }
  ],
  history: [
    { question: "¿Quién fue el primer presidente de EEUU?", options: ["Lincoln", "Washington", "Jefferson", "Roosevelt"], answer: "Washington" },
    { question: "¿En qué año terminó la Segunda Guerra Mundial?", options: ["1940", "1945", "1950", "1939"], answer: "1945" },
    { question: "¿Cuál civilización construyó las pirámides?", options: ["Aztecas", "Incas", "Egipcios", "Mayas"], answer: "Egipcios" },
    { question: "¿Quién escribió la 'Ilíada'?", options: ["Homero", "Platón", "Sófocles", "Aristóteles"], answer: "Homero" },
    { question: "¿Dónde se originó la democracia?", options: ["Roma", "Atenas", "Egipto", "Mesopotamia"], answer: "Atenas" },
    { question: "¿Quién descubrió América?", options: ["Colón", "Magallanes", "Cook", "Vespucci"], answer: "Colón" },
    { question: "¿Qué imperio cayó en 1453?", options: ["Romano", "Bizantino", "Mongol", "Egipcio"], answer: "Bizantino" },
    { question: "¿Quién fue conocido como el Libertador de América del Sur?", options: ["Simón Bolívar", "José de San Martín", "Bernardo O'Higgins", "Miguel Hidalgo"], answer: "Simón Bolívar" },
    { question: "¿En qué año se firmó la Declaración de Independencia de EEUU?", options: ["1776", "1789", "1812", "1492"], answer: "1776" },
      { question: "¿Quién fue el faraón durante la construcción de la Gran Pirámide de Giza?", options: ["Tutankamón", "Keops", "Ramsés II", "Cleopatra"], answer: "Keops" },
  { question: "¿En qué año cayó el Imperio Romano de Occidente?", options: ["476", "1453", "1492", "395"], answer: "476" },
  { question: "¿Quién lideró la Revolución Rusa de 1917?", options: ["Lenin", "Stalin", "Trotsky", "Kerenski"], answer: "Lenin" },
  { question: "¿Cuál fue la causa principal de la Primera Guerra Mundial?", options: ["Asesinato de Franz Ferdinand", "Revolución Industrial", "Imperialismo", "Tratado de Versalles"], answer: "Asesinato de Franz Ferdinand" },
  { question: "¿Quién fue el emperador francés que se coronó a sí mismo en 1804?", options: ["Napoleón Bonaparte", "Luis XVI", "Carlos X", "Robespierre"], answer: "Napoleón Bonaparte" },
  { question: "¿Qué civilización habitaba el actual México antes de la llegada de los españoles?", options: ["Azteca", "Inca", "Maya", "Olmeca"], answer: "Azteca" },
  { question: "¿En qué siglo ocurrió la Revolución Francesa?", options: ["XVII", "XVIII", "XIX", "XX"], answer: "XVIII" },
  { question: "¿Quién fue el primer hombre en orbitar la Tierra?", options: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "John Glenn"], answer: "Yuri Gagarin" },
  { question: "¿Cuál era la capital del Imperio Inca?", options: ["Cuzco", "Lima", "Quito", "La Paz"], answer: "Cuzco" },
  { question: "¿Qué invento facilitó la difusión de ideas durante el Renacimiento?", options: ["La imprenta", "La brújula", "El telescopio", "La pólvora"], answer: "La imprenta" },
  { question: "¿Qué país fue el primero en otorgar el voto femenino?", options: ["Nueva Zelanda", "Estados Unidos", "Reino Unido", "Australia"], answer: "Nueva Zelanda" },
  { question: "¿Quién fue la reina de Inglaterra durante la época isabelina?", options: ["Isabel I", "Victoria", "Ana", "María I"], answer: "Isabel I" },
  { question: "¿Qué guerra enfrentó a los estados del norte y del sur en Estados Unidos?", options: ["Guerra Civil", "Guerra de Independencia", "Guerra Franco-Prusiana", "Guerra de Secesión"], answer: "Guerra Civil" },
  { question: "¿En qué año comenzó la Revolución Industrial?", options: ["1760", "1800", "1850", "1900"], answer: "1760" },
  { question: "¿Quién fue el líder de la India en la lucha por la independencia?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Nehru", "Indira Gandhi"], answer: "Mahatma Gandhi" },
  { question: "¿Qué tratado puso fin a la Primera Guerra Mundial?", options: ["Tratado de Versalles", "Tratado de París", "Tratado de Tordesillas", "Tratado de Utrecht"], answer: "Tratado de Versalles" },
  { question: "¿Quién fue el dictador de Alemania durante la Segunda Guerra Mundial?", options: ["Adolf Hitler", "Benito Mussolini", "Joseph Stalin", "Francisco Franco"], answer: "Adolf Hitler" },
  { question: "¿Cuál fue la civilización que habitó Mesopotamia?", options: ["Sumerios", "Egipcios", "Griegos", "Romanos"], answer: "Sumerios" },
  { question: "¿Qué explorador portugués circunnavegó el mundo por primera vez?", options: ["Fernando de Magallanes", "Vasco da Gama", "Bartolomé Díaz", "Cristóbal Colón"], answer: "Fernando de Magallanes" },
  { question: "¿Qué ciudad fue destruida por la erupción del volcán Vesubio en el año 79 d.C.?", options: ["Pompeya", "Roma", "Cartago", "Atenas"], answer: "Pompeya" },
  { question: "¿Cuál fue el primer imperio en usar un sistema de leyes escritas?", options: ["Babilónico", "Egipcio", "Persa", "Griego"], answer: "Babilónico" },
  { question: "¿En qué país se originó la civilización maya?", options: ["México", "Brasil", "Argentina", "Perú"], answer: "México" },
  { question: "¿Quién fue el líder del fascismo en Italia?", options: ["Benito Mussolini", "Adolf Hitler", "Francisco Franco", "Vladimir Lenin"], answer: "Benito Mussolini" },
  { question: "¿Qué imperio fue gobernado por Gengis Kan?", options: ["Mongol", "Persa", "Romano", "Bizantino"], answer: "Mongol" },
  { question: "¿Cuál es el nombre de la nave que llevó a Cristóbal Colón a América?", options: ["La Santa María", "La Pinta", "La Niña", "La Victoria"], answer: "La Santa María" },
  { question: "¿Qué evento marcó el inicio de la Edad Media?", options: ["Caída del Imperio Romano de Occidente", "Descubrimiento de América", "Revolución Francesa", "Revolución Industrial"], answer: "Caída del Imperio Romano de Occidente" },
  { question: "¿Quién fue la emperatriz conocida como 'la zarina de todas las Rusias'?", options: ["Catalina la Grande", "Ana Bolena", "Isabel I", "María Antonieta"], answer: "Catalina la Grande" },
  { question: "¿Cuál fue la capital del Imperio Otomano?", options: ["Estambul", "Ankara", "Bagdad", "Damasco"], answer: "Estambul" },
  { question: "¿En qué guerra se utilizó por primera vez el gas mostaza?", options: ["Primera Guerra Mundial", "Segunda Guerra Mundial", "Guerra de Vietnam", "Guerra Civil Española"], answer: "Primera Guerra Mundial" },
  { question: "¿Qué líder sudafricano fue encarcelado durante 27 años y luego se convirtió en presidente?", options: ["Nelson Mandela", "Desmond Tutu", "Robert Mugabe", "Julius Nyerere"], answer: "Nelson Mandela" },
  { question: "¿Quién fue el último faraón de Egipto?", options: ["Cleopatra", "Tutankamón", "Ramsés II", "Nefertiti"], answer: "Cleopatra" },
  { question: "¿Qué imperio era conocido por sus guerreros llamados 'samuráis'?", options: ["Japón", "China", "Corea", "Vietnam"], answer: "Japón" },
  { question: "¿Cuál fue la civilización que desarrolló el alfabeto cuneiforme?", options: ["Sumerios", "Egipcios", "Griegos", "Fenicios"], answer: "Sumerios" },
  { question: "¿Quién fue el líder de la Revolución Cubana en 1959?", options: ["Fidel Castro", "Che Guevara", "Raúl Castro", "Batista"], answer: "Fidel Castro" },
  { question: "¿En qué año se firmó la Carta Magna?", options: ["1215", "1066", "1492", "1776"], answer: "1215" },
  { question: "¿Quién fue el líder del movimiento por los derechos civiles en EE.UU. durante los años 60?", options: ["Martin Luther King Jr.", "Malcolm X", "Rosa Parks", "Frederick Douglass"], answer: "Martin Luther King Jr." },
  { question: "¿Cuál fue la civilización conocida por sus templos escalonados llamados ziggurats?", options: ["Mesopotámica", "Egipcia", "Inca", "Azteca"], answer: "Mesopotámica" },
  { question: "¿Quién fue la figura central del Renacimiento italiano?", options: ["Leonardo da Vinci", "Miguel Ángel", "Donatello", "Raphael"], answer: "Leonardo da Vinci" },
  { question: "¿Cuál fue el propósito principal de las Cruzadas?", options: ["Recuperar Tierra Santa", "Expandir el Imperio Romano", "Comerciar con Asia", "Descubrir América"], answer: "Recuperar Tierra Santa" },
  { question: "¿Qué imperio fue dirigido por Julio César?", options: ["Romano", "Griego", "Egipcio", "Persa"], answer: "Romano" },
  { question: "¿Qué país fue conocido como la 'Tierra del Sol Naciente'?", options: ["Japón", "China", "Corea", "Vietnam"], answer: "Japón" },
  { question: "¿Quién fue la reina Victoria?", options: ["Reina del Reino Unido", "Reina de Francia", "Reina de España", "Reina de Rusia"], answer: "Reina del Reino Unido" },
  { question: "¿Cuál fue el conflicto armado entre los aliados y las potencias del Eje?", options: ["Segunda Guerra Mundial", "Primera Guerra Mundial", "Guerra Fría", "Guerra de Corea"], answer: "Segunda Guerra Mundial" },
  { question: "¿Qué tratado dividió América del Sur entre España y Portugal?", options: ["Tratado de Tordesillas", "Tratado de Versalles", "Tratado de París", "Tratado de Utrecht"], answer: "Tratado de Tordesillas" },
  { question: "¿Quién fue el arquitecto de la Unión Soviética tras la Segunda Guerra Mundial?", options: ["Joseph Stalin", "Vladimir Lenin", "Nikita Jrushchov", "Leon Trotsky"], answer: "Joseph Stalin" },
  { question: "¿Cuál fue el nombre de la expedición de 1519 que completó la primera circunnavegación?", options: ["Expedición de Magallanes", "Expedición de Colón", "Expedición de Vasco da Gama", "Expedición de Cook"], answer: "Expedición de Magallanes" },
  { question: "¿En qué año se construyó el Muro de Berlín?", options: ["1961", "1949", "1989", "1975"], answer: "1961" },
  { question: "¿Quién fue el fundador del Imperio Mongol?", options: ["Gengis Kan", "Kublai Kan", "Tamerlán", "Attila"], answer: "Gengis Kan" },
  { question: "¿Qué civilización precolombina habitó en la región de los Andes centrales?", options: ["Inca", "Azteca", "Maya", "Olmeca"], answer: "Inca" },
  { question: "¿Qué rey inglés firmó la Carta Magna en 1215?", options: ["Juan Sin Tierra", "Ricardo Corazón de León", "Enrique VIII", "Guillermo el Conquistador"], answer: "Juan Sin Tierra" }
  ],
  technology: [
    { question: "¿Quién es el creador de Facebook?", options: ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Elon Musk"], answer: "Mark Zuckerberg" },
    { question: "¿Qué significa CPU?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Performance Unit", "Computer Processing Unit"], answer: "Central Processing Unit" },
    { question: "¿Cuál fue el primer sistema operativo de Microsoft?", options: ["Windows 95", "MS-DOS", "Windows XP", "Windows 1.0"], answer: "MS-DOS" },
    { question: "¿Qué lenguaje de programación es conocido por su uso en desarrollo web?", options: ["Python", "Java", "JavaScript", "C++"], answer: "JavaScript" },
    { question: "¿Qué es la inteligencia artificial?", options: ["Un robot", "Un software que imita la inteligencia humana", "Un videojuego", "Una red social"], answer: "Un software que imita la inteligencia humana" },
    { question: "¿Qué dispositivo usamos para almacenar datos externamente?", options: ["CPU", "RAM", "Disco duro", "Pendrive"], answer: "Pendrive" },
      { question: "¿Quién es considerado el padre de la computación?", options: ["Alan Turing", "Bill Gates", "Steve Jobs", "Tim Berners-Lee"], answer: "Alan Turing" },
  { question: "¿Qué empresa creó el sistema operativo Android?", options: ["Apple", "Microsoft", "Google", "Samsung"], answer: "Google" },
  { question: "¿Qué significa la sigla HTML?", options: ["HyperText Markup Language", "HyperText Markdown Language", "HighText Markup Language", "HyperText Machine Language"], answer: "HyperText Markup Language" },
  { question: "¿Qué empresa lanzó el primer iPhone?", options: ["Samsung", "Apple", "Nokia", "Motorola"], answer: "Apple" },
  { question: "¿Qué tipo de dispositivo es un router?", options: ["Dispositivo de almacenamiento", "Dispositivo de red", "Dispositivo de entrada", "Dispositivo de salida"], answer: "Dispositivo de red" },
  { question: "¿Qué componente es considerado el 'cerebro' de una computadora?", options: ["CPU", "GPU", "RAM", "Disco duro"], answer: "CPU" },
  { question: "¿Qué significa RAM en informática?", options: ["Random Access Memory", "Read Access Memory", "Rapid Access Memory", "Run Access Memory"], answer: "Random Access Memory" },
  { question: "¿Cuál es el navegador web más usado en el mundo?", options: ["Firefox", "Safari", "Chrome", "Edge"], answer: "Chrome" },
  { question: "¿Qué es un firewall?", options: ["Un programa para editar fotos", "Un sistema de seguridad de red", "Un tipo de hardware", "Un lenguaje de programación"], answer: "Un sistema de seguridad de red" },
  { question: "¿Qué significa USB?", options: ["Universal Serial Bus", "United Serial Bus", "Universal Service Bus", "Unit Service Bus"], answer: "Universal Serial Bus" },
  { question: "¿Qué lenguaje de programación se utiliza principalmente para el desarrollo de apps en iOS?", options: ["Swift", "Java", "Python", "C#"], answer: "Swift" },
  { question: "¿Qué es un SSD?", options: ["Unidad de estado sólido", "Disco duro tradicional", "Software de seguridad", "Sistema de almacenamiento"], answer: "Unidad de estado sólido" },
  { question: "¿Quién fundó Microsoft?", options: ["Steve Jobs y Steve Wozniak", "Bill Gates y Paul Allen", "Mark Zuckerberg y Eduardo Saverin", "Larry Page y Sergey Brin"], answer: "Bill Gates y Paul Allen" },
  { question: "¿Cuál es la función principal de una GPU?", options: ["Procesar gráficos y videos", "Almacenar datos", "Ejecutar programas", "Gestionar la red"], answer: "Procesar gráficos y videos" },
  { question: "¿Qué es un virus informático?", options: ["Un programa malicioso", "Un hardware dañado", "Un lenguaje de programación", "Un sistema operativo"], answer: "Un programa malicioso" },
  { question: "¿Qué tecnología permite hacer pagos móviles con el teléfono?", options: ["NFC", "Bluetooth", "Wi-Fi", "Infrared"], answer: "NFC" },
  { question: "¿Qué significa IoT?", options: ["Internet of Things", "Internet of Technology", "Information on Time", "Interface of Technology"], answer: "Internet of Things" },
  { question: "¿Cuál es el principal sistema operativo para servidores?", options: ["Linux", "Windows", "MacOS", "Android"], answer: "Linux" },
  { question: "¿Qué tipo de memoria es volátil y se borra al apagar la computadora?", options: ["RAM", "SSD", "HDD", "ROM"], answer: "RAM" },
  { question: "¿Qué es la realidad aumentada?", options: ["Un videojuego", "La combinación de realidad con elementos virtuales", "Una red social", "Un sistema operativo"], answer: "La combinación de realidad con elementos virtuales" },
  { question: "¿Qué lenguaje de programación es conocido por su simplicidad y es muy usado en ciencia de datos?", options: ["Python", "Java", "C++", "Ruby"], answer: "Python" },
  { question: "¿Qué es un servidor web?", options: ["Una computadora que almacena sitios web", "Un programa para crear sitios web", "Un tipo de virus", "Una red social"], answer: "Una computadora que almacena sitios web" },
  { question: "¿Cuál es el nombre del asistente virtual de Apple?", options: ["Cortana", "Siri", "Alexa", "Google Assistant"], answer: "Siri" },
  { question: "¿Qué es el 'cloud computing'?", options: ["Almacenamiento y procesamiento de datos en la nube", "Una red social", "Un tipo de hardware", "Un lenguaje de programación"], answer: "Almacenamiento y procesamiento de datos en la nube" },
  { question: "¿Qué empresa creó el sistema operativo Windows?", options: ["Apple", "Google", "Microsoft", "IBM"], answer: "Microsoft" },
  { question: "¿Cuál es la función de un antivirus?", options: ["Eliminar virus informáticos", "Editar documentos", "Crear software", "Diseñar páginas web"], answer: "Eliminar virus informáticos" },
  { question: "¿Qué significa URL?", options: ["Uniform Resource Locator", "Universal Resource Link", "Uniform Reference Location", "Universal Reference Locator"], answer: "Uniform Resource Locator" },
  { question: "¿Qué dispositivo usamos para convertir señales digitales en señales analógicas?", options: ["Modem", "Router", "Switch", "Hub"], answer: "Modem" },
  { question: "¿Qué lenguaje se usa para dar estilo a las páginas web?", options: ["CSS", "HTML", "JavaScript", "Python"], answer: "CSS" },
  { question: "¿Cuál fue el primer motor de búsqueda en internet?", options: ["Google", "Yahoo", "AltaVista", "Bing"], answer: "AltaVista" },
  { question: "¿Qué es el 'phishing'?", options: ["Un tipo de fraude electrónico", "Un software de seguridad", "Un tipo de hardware", "Un lenguaje de programación"], answer: "Un tipo de fraude electrónico" },
  { question: "¿Qué empresa desarrolló el sistema operativo Linux?", options: ["Ninguna, es software libre desarrollado por la comunidad", "Microsoft", "Apple", "Google"], answer: "Ninguna, es software libre desarrollado por la comunidad" },
  { question: "¿Cuál es la capacidad estándar de un CD?", options: ["700 MB", "4.7 GB", "1 GB", "650 MB"], answer: "700 MB" },
  { question: "¿Qué es la ciberseguridad?", options: ["Protección de sistemas informáticos contra ataques", "Diseño de software", "Creación de hardware", "Un tipo de red"], answer: "Protección de sistemas informáticos contra ataques" },
  { question: "¿Qué es un 'bug' en programación?", options: ["Un error en el código", "Una función nueva", "Un tipo de software", "Un lenguaje de programación"], answer: "Un error en el código" },
  { question: "¿Cuál fue el primer videojuego comercial?", options: ["Pong", "Tetris", "Space Invaders", "Pac-Man"], answer: "Pong" },
  { question: "¿Qué dispositivo es usado para capturar imágenes y videos?", options: ["Micrófono", "Cámara", "Monitor", "Altavoz"], answer: "Cámara" },
  { question: "¿Qué es la nube en tecnología?", options: ["Almacenamiento remoto de datos", "Un tipo de disco duro", "Un programa de edición", "Un virus"], answer: "Almacenamiento remoto de datos" },
  { question: "¿Qué significa AI en tecnología?", options: ["Artificial Intelligence", "Automatic Interface", "Applied Informatics", "Advanced Internet"], answer: "Artificial Intelligence" },
  { question: "¿Qué dispositivo usamos para ingresar datos a una computadora?", options: ["Teclado", "Monitor", "Impresora", "Altavoz"], answer: "Teclado" },
  { question: "¿Qué red social pertenece a Mark Zuckerberg?", options: ["Twitter", "Instagram", "Facebook", "TikTok"], answer: "Facebook" },
  { question: "¿Qué empresa creó el primer microprocesador comercial?", options: ["Intel", "AMD", "IBM", "Apple"], answer: "Intel" },
  { question: "¿Qué protocolo se usa para enviar correos electrónicos?", options: ["SMTP", "HTTP", "FTP", "TCP"], answer: "SMTP" },
  { question: "¿Cuál es el nombre del fundador de Tesla y SpaceX?", options: ["Jeff Bezos", "Elon Musk", "Bill Gates", "Steve Jobs"], answer: "Elon Musk" },
  { question: "¿Qué significa API?", options: ["Application Programming Interface", "Applied Program Internet", "Automated Process Interface", "Application Protocol Internet"], answer: "Application Programming Interface" },
  { question: "¿Qué tecnología es usada para crear criptomonedas?", options: ["Blockchain", "Big Data", "Cloud Computing", "Artificial Intelligence"], answer: "Blockchain" },
  { question: "¿Qué es un 'cookie' en internet?", options: ["Un archivo que almacena datos del usuario", "Un virus", "Un lenguaje de programación", "Un tipo de hardware"], answer: "Un archivo que almacena datos del usuario" },
  { question: "¿Qué significa HTTPS?", options: ["Protocolo seguro de transferencia de hipertexto", "Protocolo de transferencia de hipertexto", "Protocolo de red", "Protocolo de seguridad"], answer: "Protocolo seguro de transferencia de hipertexto" },
  { question: "¿Qué es un bit?", options: ["La unidad mínima de información en informática", "Un tipo de hardware", "Un lenguaje de programación", "Un sistema operativo"], answer: "La unidad mínima de información en informática" },
  { question: "¿Cuál es el nombre del asistente virtual de Amazon?", options: ["Alexa", "Siri", "Cortana", "Google Assistant"], answer: "Alexa" },
  { question: "¿Qué empresa desarrolló el asistente virtual llamado Cortana?", options: ["Microsoft", "Google", "Apple", "Amazon"], answer: "Microsoft" },
  { question: "¿Qué es un 'kernel' en informática?", options: ["El núcleo del sistema operativo", "Un tipo de virus", "Un lenguaje de programación", "Un hardware"], answer: "El núcleo del sistema operativo" }
  ],
  sports: [
    { question: "¿En qué deporte se usa un balón ovalado?", options: ["Fútbol", "Baloncesto", "Rugby", "Voleibol"], answer: "Rugby" },
    { question: "¿Cuántos jugadores tiene un equipo de fútbol?", options: ["9", "10", "11", "12"], answer: "11" },
    { question: "¿Quién tiene el récord de más goles en la historia del fútbol?", options: ["Pelé", "Cristiano Ronaldo", "Lionel Messi", "Maradona"], answer: "Cristiano Ronaldo" },
    { question: "¿Dónde se celebraron los primeros Juegos Olímpicos modernos?", options: ["Atenas", "París", "Londres", "Roma"], answer: "Atenas" },
    { question: "¿Qué deporte utiliza una raqueta y una pelota amarilla?", options: ["Tenis", "Bádminton", "Ping Pong", "Squash"], answer: "Tenis" },
      { question: "¿Cuántos sets se juegan normalmente en un partido de tenis masculino de Grand Slam?", options: ["3", "5", "7", "4"], answer: "5" },
  { question: "¿Qué país ganó la Copa Mundial de Fútbol en 2018?", options: ["Brasil", "Alemania", "Francia", "Argentina"], answer: "Francia" },
  { question: "¿En qué deporte se utiliza un disco llamado 'puck'?", options: ["Hockey sobre hielo", "Fútbol americano", "Baloncesto", "Rugby"], answer: "Hockey sobre hielo" },
  { question: "¿Cuántos jugadores tiene un equipo de baloncesto en cancha?", options: ["4", "5", "6", "7"], answer: "5" },
  { question: "¿Quién es conocido como 'El Rey del Fútbol'?", options: ["Pelé", "Maradona", "Cristiano Ronaldo", "Lionel Messi"], answer: "Pelé" },
  { question: "¿Cuál es el deporte nacional de Japón?", options: ["Judo", "Sumo", "Kárate", "Aikido"], answer: "Sumo" },
  { question: "¿Qué disciplina olímpica combina esquí de fondo y tiro con rifle?", options: ["Biathlon", "Pentatlón", "Triatlón", "Pentatlón moderno"], answer: "Biathlon" },
  { question: "¿Qué país inventó el fútbol?", options: ["Brasil", "Inglaterra", "Italia", "España"], answer: "Inglaterra" },
  { question: "¿Cuál es el nombre del torneo anual de tenis que se juega en césped en Londres?", options: ["US Open", "Roland Garros", "Wimbledon", "Australian Open"], answer: "Wimbledon" },
  { question: "¿En qué deporte se usa un palo y una bola para embocar en un hoyo?", options: ["Golf", "Cricket", "Hockey", "Polo"], answer: "Golf" }
  ],
  arts_culture: [
  { question: "¿Quién pintó 'La Mona Lisa'?", options: ["Miguel Ángel", "Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh"], answer: "Leonardo da Vinci" },
  { question: "¿Qué estilo musical es originario de Jamaica?", options: ["Reggae", "Salsa", "Jazz", "Blues"], answer: "Reggae" },
  { question: "¿Qué escritor es famoso por sus obras de teatro en inglés?", options: ["Shakespeare", "Cervantes", "Dante", "Goethe"], answer: "Shakespeare" },
  { question: "¿Cuál es la capital mundial del cine?", options: ["Los Ángeles", "París", "Bollywood", "Nueva York"], answer: "Los Ángeles" },
  { question: "¿En qué país se originó el flamenco?", options: ["Portugal", "España", "Italia", "Grecia"], answer: "España" },

  { question: "¿Quién compuso la 'Novena Sinfonía'?", options: ["Mozart", "Beethoven", "Bach", "Chopin"], answer: "Beethoven" },
  { question: "¿Qué movimiento artístico está asociado con Salvador Dalí?", options: ["Cubismo", "Surrealismo", "Impresionismo", "Expresionismo"], answer: "Surrealismo" },
  { question: "¿Qué país es famoso por su teatro Noh?", options: ["China", "Japón", "Corea", "India"], answer: "Japón" },
  { question: "¿Qué novela escribió Gabriel García Márquez?", options: ["Cien años de soledad", "Don Quijote", "El amor en los tiempos del cólera", "La ciudad y los perros"], answer: "Cien años de soledad" },
  { question: "¿Quién es el pintor del mural 'Guernica'?", options: ["Pablo Picasso", "Diego Rivera", "Frida Kahlo", "Joan Miró"], answer: "Pablo Picasso" },

  { question: "¿En qué país se originó el ballet clásico?", options: ["Francia", "Italia", "Rusia", "España"], answer: "Italia" },
  { question: "¿Quién escribió la ópera 'La Traviata'?", options: ["Verdi", "Mozart", "Puccini", "Wagner"], answer: "Verdi" },
  { question: "¿Qué corriente literaria pertenece a Franz Kafka?", options: ["Realismo", "Modernismo", "Existencialismo", "Surrealismo"], answer: "Existencialismo" },
  { question: "¿Cuál es el nombre del famoso festival anual de arte en Venecia?", options: ["Bienal de Venecia", "Carnaval de Venecia", "Festival de Cine de Venecia", "Venecia Jazz Festival"], answer: "Bienal de Venecia" },
  { question: "¿Qué arquitectura es característica de Antoni Gaudí?", options: ["Barroco", "Modernismo", "Gótico", "Románico"], answer: "Modernismo" },

  { question: "¿Qué pintor es conocido por sus girasoles?", options: ["Claude Monet", "Vincent van Gogh", "Paul Cézanne", "Henri Matisse"], answer: "Vincent van Gogh" },
  { question: "¿Qué país es el origen del tango?", options: ["Brasil", "Argentina", "Chile", "México"], answer: "Argentina" },
  { question: "¿Quién escribió 'La Divina Comedia'?", options: ["Dante Alighieri", "Boccaccio", "Petrarca", "Goethe"], answer: "Dante Alighieri" },
  { question: "¿Cuál es la película más premiada en la historia de los Óscar?", options: ["Titanic", "Ben-Hur", "El Señor de los Anillos: El Retorno del Rey", "La La Land"], answer: "El Señor de los Anillos: El Retorno del Rey" },
  { question: "¿Qué instrumento musical es típico en la música flamenca?", options: ["Guitarra", "Piano", "Violín", "Saxofón"], answer: "Guitarra" },

  { question: "¿Quién fue la famosa pintora mexicana que sufrió un accidente que influyó en su arte?", options: ["Frida Kahlo", "Georgia O'Keeffe", "Mary Cassatt", "Artemisia Gentileschi"], answer: "Frida Kahlo" },
  { question: "¿Qué corriente artística se caracteriza por la representación de la luz y el color, con artistas como Monet y Renoir?", options: ["Impresionismo", "Cubismo", "Surrealismo", "Barroco"], answer: "Impresionismo" },
  { question: "¿En qué país se originó la ópera?", options: ["Italia", "Alemania", "Francia", "Austria"], answer: "Italia" },
  { question: "¿Quién escribió 'Cien años de soledad'?", options: ["Gabriel García Márquez", "Mario Vargas Llosa", "Jorge Luis Borges", "Pablo Neruda"], answer: "Gabriel García Márquez" },
  { question: "¿Qué famoso escultor creó 'El Pensador'?", options: ["Auguste Rodin", "Michelangelo", "Donatello", "Gian Lorenzo Bernini"], answer: "Auguste Rodin" },

  { question: "¿Qué estilo arquitectónico es característico de las catedrales europeas medievales?", options: ["Gótico", "Románico", "Barroco", "Neoclásico"], answer: "Gótico" },
  { question: "¿Qué país es conocido por la música tradicional llamada 'Fado'?", options: ["España", "Portugal", "Italia", "Grecia"], answer: "Portugal" },
  { question: "¿Cuál es el nombre del famoso cuadro de Edvard Munch que representa un grito?", options: ["El Grito", "La Persistencia de la Memoria", "La Noche Estrellada", "Las Meninas"], answer: "El Grito" },
  { question: "¿Quién compuso 'El Cascanueces'?", options: ["Tchaikovsky", "Beethoven", "Mozart", "Chopin"], answer: "Tchaikovsky" },
  { question: "¿Qué ciudad es famosa por su carnaval con máscaras elaboradas?", options: ["Venecia", "Río de Janeiro", "Nueva Orleans", "Niza"], answer: "Venecia" }
],
  math: [
    { question: "¿Cuál es el resultado de 7 x 8?", options: ["54", "56", "58", "60"], answer: "56" },
    { question: "¿Cuál es el valor de Pi (aproximado)?", options: ["3.14", "2.71", "1.61", "3.41"], answer: "3.14" },
    { question: "¿Qué es un número primo?", options: ["Número divisible solo por 1 y por sí mismo", "Número par", "Número impar", "Número negativo"], answer: "Número divisible solo por 1 y por sí mismo" },
    { question: "¿Cuánto es la raíz cuadrada de 81?", options: ["7", "8", "9", "10"], answer: "9" },
    { question: "¿Qué representa el ángulo recto?", options: ["45 grados", "60 grados", "90 grados", "180 grados"], answer: "90 grados" },
     { question: "¿Cuánto es 12 x 12?", options: ["124", "142", "144", "154"], answer: "144" },
  { question: "¿Cuál es el número romano para 50?", options: ["L", "C", "V", "X"], answer: "L" },
  { question: "¿Cuánto es 100 dividido entre 4?", options: ["20", "25", "30", "40"], answer: "25" },
  { question: "¿Qué figura tiene tres lados?", options: ["Cuadrado", "Círculo", "Triángulo", "Pentágono"], answer: "Triángulo" },
  { question: "¿Cómo se llama un polígono de 5 lados?", options: ["Hexágono", "Cuadrado", "Pentágono", "Heptágono"], answer: "Pentágono" },
  { question: "¿Cuánto es 15 + 27?", options: ["42", "43", "44", "45"], answer: "42" },
  { question: "¿Cuál es el opuesto del número -10?", options: ["-10", "0", "10", "1"], answer: "10" },
  { question: "¿Qué representa el símbolo %?", options: ["Perímetro", "Promedio", "Porcentaje", "Potencia"], answer: "Porcentaje" },
  { question: "¿Qué es un número par?", options: ["Divisible entre 2", "Mayor que 0", "Menor que 0", "Impar"], answer: "Divisible entre 2" },
  { question: "¿Cuánto es 2 elevado a la 5?", options: ["16", "32", "64", "25"], answer: "32" },
  { question: "¿Cuál es la mitad de 250?", options: ["100", "115", "125", "135"], answer: "125" },
  { question: "¿Qué tipo de ángulo mide menos de 90 grados?", options: ["Obtuso", "Llano", "Recto", "Agudo"], answer: "Agudo" },
  { question: "¿Qué operación se usa para encontrar el área de un rectángulo?", options: ["Largo + ancho", "Largo x ancho", "2 x largo + ancho", "Largo ÷ ancho"], answer: "Largo x ancho" },
  { question: "¿Qué es una fracción?", options: ["Una multiplicación", "Una división de dos números", "Un número primo", "Un número par"], answer: "Una división de dos números" },
  { question: "¿Cuánto es 3 al cubo (3³)?", options: ["6", "9", "27", "18"], answer: "27" },
  { question: "¿Qué nombre recibe un polígono de 8 lados?", options: ["Hexágono", "Octágono", "Heptágono", "Decágono"], answer: "Octágono" },
  { question: "¿Qué es un múltiplo de 5?", options: ["Número que termina en 5 o 0", "Número impar", "Número negativo", "Número primo"], answer: "Número que termina en 5 o 0" },
  { question: "¿Cuál es el valor absoluto de -20?", options: ["-20", "0", "20", "10"], answer: "20" },
  { question: "¿Qué número falta en la secuencia: 5, 10, __, 20?", options: ["11", "12", "13", "15"], answer: "15" },
  { question: "¿Cómo se llama el resultado de una suma?", options: ["Producto", "Diferencia", "Suma", "Total"], answer: "Total" }
  ],
  peliculas_series: [
    { question: "¿En qué año se estrenó la película 'Titanic'?", options: ["1995", "1997", "1999", "2000"], answer: "1997" },
    { question: "¿Cuál es el nombre del personaje principal en la serie 'Friends'?", options: ["Ross Geller", "Chandler Bing", "Rachel Green", "Todos los anteriores"], answer: "Todos los anteriores" },
    { question: "¿Qué actor interpreta a 'El Señor de los Anillos' Frodo Bolsón?", options: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Orlando Bloom"], answer: "Elijah Wood" },
    { question: "¿Cuál de estas series se emitió primero?", options: ["Breaking Bad", "The Sopranos", "Lost", "Game of Thrones"], answer: "The Sopranos" },
    { question: "¿En qué año se estrenó la serie 'Stranger Things'?", options: ["2015", "2016", "2017", "2018"], answer: "2016" },
    { question: "¿Cuál es el nombre del villano en la película 'El Rey León' de 1994?", options: ["Scar", "Mufasa", "Timon", "Pumba"], answer: "Scar" },
    { question: "¿Qué película protagonizó Keanu Reeves como un conductor llamado John Wick?", options: ["John Wick", "Matrix", "Speed", "Constantine"], answer: "John Wick" },
    { question: "¿Qué serie de televisión tiene a un grupo de amigos que viven en Nueva York y se estrenó en 1994?", options: ["Seinfeld", "Friends", "The Fresh Prince of Bel-Air", "ER"], answer: "Friends" },
    { question: "¿Quién dirigió la película 'Pulp Fiction'?", options: ["Quentin Tarantino", "Steven Spielberg", "Martin Scorsese", "James Cameron"], answer: "Quentin Tarantino" },
    { question: "¿En qué serie aparece el personaje Walter White?", options: ["Better Call Saul", "Breaking Bad", "The Wire", "Narcos"], answer: "Breaking Bad" },
    { question: "¿Qué película ganó el Óscar a Mejor Película en 2010?", options: ["Avatar", "The Hurt Locker", "Inception", "Up"], answer: "The Hurt Locker" },
    { question: "¿Cuál es el nombre de la serie con zombies que empezó en 2010 y se basa en un cómic?", options: ["The Walking Dead", "Z Nation", "Fear the Walking Dead", "Black Summer"], answer: "The Walking Dead" },
    { question: "¿Qué actor protagonizó la saga de películas 'Piratas del Caribe' como Jack Sparrow?", options: ["Johnny Depp", "Orlando Bloom", "Leonardo DiCaprio", "Brad Pitt"], answer: "Johnny Depp" },
    { question: "¿Cuál fue la última temporada emitida de 'Game of Thrones'?", options: ["Temporada 6", "Temporada 7", "Temporada 8", "Temporada 9"], answer: "Temporada 8" },
    { question: "¿En qué año se estrenó la película 'Matrix'?", options: ["1997", "1999", "2001", "2003"], answer: "1999" },
    { question: "¿Cuál es la serie que gira en torno a un hombre que cambia su identidad para evitar ser capturado por la CIA?", options: ["Homeland", "24", "Alias", "Lost"], answer: "Alias" },
    { question: "¿En qué película aparece el personaje 'Forrest Gump'?", options: ["Forrest Gump", "Cast Away", "Saving Private Ryan", "Apollo 13"], answer: "Forrest Gump" },
    { question: "¿Qué serie creada por Vince Gilligan es una precuela de 'Breaking Bad'?", options: ["Better Call Saul", "Narcos", "Ozark", "Fargo"], answer: "Better Call Saul" },
    { question: "¿Qué película de animación de Pixar fue estrenada en 2015?", options: ["Inside Out", "Coco", "Toy Story 3", "Up"], answer: "Inside Out" },
    { question: "¿Qué actriz protagoniza la serie 'The Crown' como la Reina Isabel II en sus primeros años?", options: ["Claire Foy", "Olivia Colman", "Emma Corrin", "Helena Bonham Carter"], answer: "Claire Foy" }
  ],
  translation_phrases: [
  {
    question: "¿Cómo se traduce la frase 'It's raining cats and dogs' al español?",
    options: [
      "Está lloviendo mucho",
      "Está lloviendo gatos y perros",
      "Hace sol y calor",
      "Está nevando"
    ],
    answer: "Está lloviendo mucho"
  },
  {
    question: "¿Qué significa en inglés la expresión 'Buscarle cinco pies al gato'?",
    options: [
      "To look for problems where there are none",
      "To take a nap",
      "To cook dinner",
      "To buy a cat"
    ],
    answer: "To look for problems where there are none"
  },
  {
    question: "¿Cómo se dice en inglés 'No hay mal que por bien no venga'?",
    options: [
      "Every cloud has a silver lining",
      "Better late than never",
      "Actions speak louder than words",
      "The early bird catches the worm"
    ],
    answer: "Every cloud has a silver lining"
  },
  {
    question: "Traduce al español: 'Break a leg!'",
    options: [
      "¡Rómpete una pierna!",
      "¡Buena suerte!",
      "¡Cuidado!",
      "¡Diviértete!"
    ],
    answer: "¡Buena suerte!"
  },
  {
    question: "¿Cómo se traduce 'Once in a blue moon' al español?",
    options: [
      "De vez en cuando",
      "Una vez en la vida",
      "Nunca jamás",
      "Muy raramente"
    ],
    answer: "Muy raramente"
  },
  {
    question: "¿Qué significa la expresión 'Tirar la toalla' en inglés?",
    options: [
      "To give up",
      "To clean up",
      "To throw a towel",
      "To wash clothes"
    ],
    answer: "To give up"
  },
  {
    question: "¿Cómo se dice en inglés 'Estar en las nubes'?",
    options: [
      "To be daydreaming",
      "To be on the ground",
      "To be in trouble",
      "To be angry"
    ],
    answer: "To be daydreaming"
  },
  {
    question: "Traduce al español: 'Hit the sack.'",
    options: [
      "Ir a la cama",
      "Golpear la bolsa",
      "Correr rápido",
      "Salir a caminar"
    ],
    answer: "Ir a la cama"
  },
  {
    question: "¿Cómo se traduce la expresión 'Más vale tarde que nunca' al inglés?",
    options: [
      "Better late than never",
      "Time is money",
      "Early bird catches the worm",
      "No pain, no gain"
    ],
    answer: "Better late than never"
  },
  {
    question: "¿Qué significa 'Costar un ojo de la cara' en inglés?",
    options: [
      "To cost an arm and a leg",
      "To be cheap",
      "To be free",
      "To be expensive but worth it"
    ],
    answer: "To cost an arm and a leg"
  },
  {
    question: "¿Cómo se dice en español 'To spill the beans'?",
    options: [
      "Revelar un secreto",
      "Derramar los frijoles",
      "Esconder algo",
      "Romper algo"
    ],
    answer: "Revelar un secreto"
  },
  {
    question: "Traduce al inglés: 'A caballo regalado no se le mira el diente.'",
    options: [
      "Don't look a gift horse in the mouth",
      "Don't count your chickens before they hatch",
      "The grass is always greener on the other side",
      "Actions speak louder than words"
    ],
    answer: "Don't look a gift horse in the mouth"
  },
  {
    question: "¿Qué significa en español 'To bite the bullet'?",
    options: [
      "Aceptar una situación difícil",
      "Morder una bala",
      "Huir de un problema",
      "Llorar mucho"
    ],
    answer: "Aceptar una situación difícil"
  },
  {
    question: "¿Cómo se traduce la frase 'No pain, no gain' al español?",
    options: [
      "Sin dolor no hay ganancia",
      "El dolor es pasajero",
      "Nunca te rindas",
      "Más vale prevenir que curar"
    ],
    answer: "Sin dolor no hay ganancia"
  },
  {
    question: "¿Qué significa la expresión 'Llevarse el gato al agua' en inglés?",
    options: [
      "To succeed against the odds",
      "To feed a cat",
      "To lose a bet",
      "To take a nap"
    ],
    answer: "To succeed against the odds"
  }
]
};
